image: node:latest

cache:
  key: ${CI_COMMIT_REF_SLUG}
  paths:
    - node_modules/

stages:
  - setup
  - test
  - build
  - publish

npm ci:
  stage: setup
  script:
    - npm ci

code quality:
  stage: test
  script:
    - npm run lint

npm outdated:
  stage: test
  script:
    - npm outdated
  allow_failure: true

security scan:
  stage: test
  script:
    - npm audit
  allow_failure: true

test:
  stage: test
  script:
    - npm test
  coverage: '/All files[^|]*\|[^|]*\s+([\d\.]+)/'

webpack build:
  stage: build
  script:
    - npm run build

publish:
  stage: publish
  only:
    - tags
    - triggers
  script:
    - echo '//registry.npmjs.org/:_authToken=${NPM_TOKEN}' > .npmrc
    - npm publish
  environment:
    name: npm
    url: https://www.npmjs.com/package/@formschema/native
