image: node:latest

cache:
  key: ${CI_COMMIT_REF_SLUG}
  paths:
    - node_modules/
    - dist/

stages:
  - setup
  - test
  - build
  - publish

npm ci:
  stage: setup
  script:
    - npm ci

code quality:
  stage: test
  script:
    - npm run lint

npm outdated:
  stage: test
  script:
    - npm outdated
  allow_failure: true

security scan:
  stage: test
  script:
    - npm audit --only=prod
  allow_failure: true

test & coverage:
  stage: test
  script:
    - npm test
  coverage: '/All files[^|]*\|[^|]*\s+([\d\.]+)/'
  artifacts:
    paths:
      - coverage/

webpack build:
  stage: build
  script:
    - npm run build
    - rm -f dist/*.html
  artifacts:
    paths:
      - dist
    expire_in: 4 weeks

coverage report:
  stage: publish
  dependencies:
    - test & coverage
  script:
    - mv coverage/lcov-report/ public/
  artifacts:
    paths:
      - public
  only:
    - master
  environment:
    name: coverage report
    url: https://formschema.gitlab.io/native

package:
  stage: publish
  only:
    - tags
  script:
    - npm pack
  artifacts:
    paths:
      - ./*.tgz

publish on npm:
  stage: publish
  only:
    - tags
    - triggers
  script:
    - echo '//registry.npmjs.org/:_authToken=${NPM_TOKEN}' > .npmrc
    - npm publish
  environment:
    name: npm
    url: https://www.npmjs.com/package/@formschema/native
